name: Build and deploy Node.js app to Azure Web App - helloExpressHI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'helloExpressHI'
          slot-name: 'production'
          package: .
          publish-profile: <publishData><publishProfile profileName="helloExpressHI - Web Deploy" publishMethod="MSDeploy" publishUrl="helloexpresshi.scm.azurewebsites.net:443" msdeploySite="helloExpressHI" userName="$helloExpressHI" userPWD="xQC3EmBP4NBjM1BQgma5gxKpcD0x7BmqsMijpyiJg5kg9w4h7mpuDaLx78EY" destinationAppUrl="https://helloexpresshi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="helloExpressHI - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-hk1-031.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="helloExpressHI\$helloExpressHI" userPWD="xQC3EmBP4NBjM1BQgma5gxKpcD0x7BmqsMijpyiJg5kg9w4h7mpuDaLx78EY" destinationAppUrl="https://helloexpresshi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="helloExpressHI - Zip Deploy" publishMethod="ZipDeploy" publishUrl="helloexpresshi.scm.azurewebsites.net:443" userName="$helloExpressHI" userPWD="xQC3EmBP4NBjM1BQgma5gxKpcD0x7BmqsMijpyiJg5kg9w4h7mpuDaLx78EY" destinationAppUrl="https://helloexpresshi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="helloExpressHI - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-hk1-031dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="helloExpressHI\$helloExpressHI" userPWD="xQC3EmBP4NBjM1BQgma5gxKpcD0x7BmqsMijpyiJg5kg9w4h7mpuDaLx78EY" destinationAppUrl="https://helloexpresshi.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>